[package]
name = "admarusd"
version = "0.1.0"
edition = "2021"

[dependencies]
kamilata = {path = "../../kamilata"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
axum = "0.6"
isahc = "1.7"
